name: Build and Deploy Jekyll Site to /docs

on:
  push:
    branches: [main]

permissions:
  contents: write  # Needed to push commits back to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Needed to push commits

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site into docs/
        run: bundle exec jekyll build -d docs

      - name: Commit and push built site to main branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Build site and deploy to /docs [skip ci]" || echo "No changes to commit"
          git push origin main
